# Generated by Django 4.1.7 on 2023-03-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                ("id_tutor", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=30)),
                ("telefone", models.CharField(max_length=15)),
                ("cidade", models.CharField(max_length=35)),
                ("sobre", models.CharField(max_length=255)),
            ],
        ),
    ]
