# Generated by Django 4.1.7 on 2023-03-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id_pet", models.AutoField(primary_key=True, serialize=False)),
                ("nome_pet", models.CharField(max_length=30)),
                ("personalidade", models.CharField(max_length=30)),
                ("porte", models.CharField(max_length=30)),
                ("especie", models.CharField(max_length=15)),
                ("cidade_pet", models.CharField(max_length=35)),
                ("sobre_pet", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("I", "Indisponível"),
                            ("D", "Disponível"),
                            ("E", "Em espera"),
                            ("A", "Adotado"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
