# Generated by Django 4.1.7 on 2023-03-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0002_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="email",
            field=models.EmailField(default=" ", max_length=255),
        ),
    ]
