# Generated by Django 4.1.7 on 2023-03-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0003_tutor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="raca",
            field=models.CharField(default=" ", max_length=100),
        ),
    ]
