# Generated by Django 4.1.7 on 2023-04-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0005_alter_pet_raca_alter_tutor_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor", name="cidade", field=models.CharField(max_length=255),
        ),
    ]
