# Generated by Django 4.1.7 on 2023-04-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0007_alter_tutor_nome_alter_tutor_telefone"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet", name="adotado", field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pet",
            name="foto_pet",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="pet",
            name="idade_pet",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tutor",
            name="foto_tutor",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="Adocao",
            fields=[
                ("id_adocao", models.AutoField(primary_key=True, serialize=False)),
                ("data_adocao", models.DateField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projeto.pet"
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projeto.tutor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Abrigo",
            fields=[
                ("id_abrigo", models.AutoField(primary_key=True, serialize=False)),
                ("email_abrigo", models.EmailField(max_length=255, unique=True)),
                ("nome_abrigo", models.CharField(max_length=255)),
                ("telefone_abrigo", models.CharField(max_length=25)),
                ("cidade_abrigo", models.CharField(max_length=255)),
                ("sobre_abrigo", models.CharField(max_length=255)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projeto.pet"
                    ),
                ),
            ],
        ),
    ]
