# Generated by Django 4.1.7 on 2023-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0009_remove_abrigo_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="abrigo",
            name="foto_abrigo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
