# Generated by Django 4.1.7 on 2023-04-03 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0012_alter_abrigo_cidade_abrigo_alter_pet_cidade_pet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abrigo",
            name="cidade_abrigo",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="cidade_pet",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="nome_pet",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="personalidade",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="porte",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="raca",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="sobre_pet",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="cidade",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="nome",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "/^[a-z][a-z\\s]*$/", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
    ]
