# Generated by Django 4.1.7 on 2023-04-03 18:56

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0013_alter_abrigo_cidade_abrigo_alter_pet_cidade_pet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abrigo",
            name="cidade_abrigo",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="abrigo",
            name="nome_abrigo",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9_ ]*$", "Inclua apenas letras e números"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="cidade_pet",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="nome_pet",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="personalidade",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="porte",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="raca",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="sobre_pet",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="cidade",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="nome",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="sobre",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ ]*$", "Não inclua números neste campo"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=14, region="BR"
            ),
        ),
    ]
