# Generated by Django 4.1.7 on 2023-04-03 18:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        (
            "projeto",
            "0014_alter_abrigo_cidade_abrigo_alter_abrigo_nome_abrigo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=14, region="BR"
            ),
        ),
    ]
