# Generated by Django 4.1.7 on 2023-04-03 19:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0017_alter_abrigo_cidade_abrigo_alter_pet_cidade_pet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=14, region=None
            ),
        ),
    ]
