# Generated by Django 4.1.7 on 2023-04-03 19:24

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0018_alter_tutor_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abrigo",
            name="nome_abrigo",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ áàâãéèêíïóôõöúçñ]*$",
                        "Não inclua números neste campo",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="telefone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="BR", unique=True
            ),
        ),
    ]
