# Generated by Django 4.1.7 on 2023-04-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0019_alter_abrigo_nome_abrigo_alter_tutor_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor", name="telefone", field=models.CharField(max_length=25),
        ),
    ]
