# Generated by Django 4.1.7 on 2023-04-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0020_alter_tutor_telefone"),
    ]

    operations = [
        migrations.RemoveField(model_name="pet", name="especie",),
        migrations.RemoveField(model_name="pet", name="personalidade",),
        migrations.RemoveField(model_name="pet", name="porte",),
        migrations.RemoveField(model_name="pet", name="raca",),
        migrations.RemoveField(model_name="pet", name="status",),
        migrations.AddField(
            model_name="pet",
            name="id_abrigo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projeto.abrigo",
            ),
        ),
    ]
