# Generated by Django 4.1.7 on 2023-04-04 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0021_remove_pet_especie_remove_pet_personalidade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AddField(
            model_name="tutor",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="staff status"),
        ),
        migrations.AddField(
            model_name="tutor",
            name="is_tutor",
            field=models.BooleanField(default=False, verbose_name="Tutor"),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="nome",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ áàâãéèêíïóôõöúçñ]*$",
                        "Não inclua números neste campo",
                    )
                ],
                verbose_name="Nome completo",
            ),
        ),
        migrations.AlterField(
            model_name="tutor",
            name="telefone",
            field=models.CharField(max_length=25, verbose_name="Telefone"),
        ),
    ]
