# Generated by Django 4.1.7 on 2023-04-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0022_tutor_is_active_tutor_is_staff_tutor_is_tutor_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="tutor", name="is_active",),
        migrations.RemoveField(model_name="tutor", name="is_staff",),
        migrations.RemoveField(model_name="tutor", name="is_tutor",),
    ]
