# Generated by Django 4.1.7 on 2023-04-04 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0023_remove_tutor_is_active_remove_tutor_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="id_abrigo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projeto.abrigo"
            ),
        ),
    ]
