# Generated by Django 4.1.7 on 2023-04-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0025_user_alter_pet_id_abrigo"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="date_joined",),
    ]
