# Generated by Django 4.1.7 on 2023-04-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0026_remove_user_date_joined"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="passwor1", new_name="password1",
        ),
    ]
