# Generated by Django 4.1.7 on 2023-04-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0027_rename_passwor1_user_password1"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="password1", new_name="password",
        ),
    ]
