# Generated by Django 4.1.7 on 2023-04-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0028_rename_password1_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
