# Generated by Django 4.1.7 on 2023-04-06 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0029_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_shelter",
            field=models.BooleanField(default=False, verbose_name="É Abrigo"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_tutor",
            field=models.BooleanField(default=False, verbose_name="É Tutor"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=35, verbose_name="Senha"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z_ áàâãéèêíïóôõöúçñ]*$",
                        "Não inclua números neste campo",
                    )
                ],
                verbose_name="Usuário",
            ),
        ),
    ]
