# Generated by Django 4.1.7 on 2023-04-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0030_alter_user_is_active_alter_user_is_shelter_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutor", old_name="email", new_name="email_tutor",
        ),
    ]
