# Generated by Django 4.1.7 on 2023-04-08 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0032_account"),
    ]

    operations = [
        migrations.DeleteModel(name="Account",),
        migrations.DeleteModel(name="User",),
    ]
