# Generated by Django 4.1.7 on 2023-04-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0033_delete_account_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet", old_name="id_abrigo", new_name="abrigo",
        ),
    ]
