# Generated by Django 4.1.7 on 2023-04-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0034_rename_id_abrigo_pet_abrigo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet", old_name="abrigo", new_name="nome_abrigo",
        ),
    ]
